[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'npm install --production=false',
  'cd client && npm install --production=false'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'node server.js'